# Generated by Django 5.0 on 2023-12-13 20:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_name', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=50, null=True)),
                ('time_start', models.IntegerField()),
                ('duration', models.CharField(max_length=50, null=True)),
                ('frequency', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=50, null=True)),
                ('retention_period', models.CharField(max_length=100, null=True)),
                ('current_members', models.IntegerField(default=1)),
                ('study_description', models.CharField(max_length=200, null=True)),
                ('bank_account', models.CharField(default=0, max_length=6, validators=[django.core.validators.RegexValidator(message='Bank account must be 6 digits.', regex='^\\d{6}$')])),
                ('max_participant', models.IntegerField()),
            ],
            options={
                'db_table': 'study',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_code', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='StudyBoard',
            fields=[
                ('study_board_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicomapp.member')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicomapp.study')),
            ],
            options={
                'db_table': 'study_board',
            },
        ),
        migrations.CreateModel(
            name='StudyComment',
            fields=[
                ('study_board_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicomapp.member')),
                ('study_board_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicomapp.studyboard')),
            ],
            options={
                'db_table': 'study_comment',
            },
        ),
        migrations.CreateModel(
            name='StudyMember',
            fields=[
                ('study_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicomapp.member')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicomapp.study')),
            ],
            options={
                'db_table': 'study_member',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='university_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicomapp.university'),
        ),
    ]
